Document: libcassandra
Title: Debian libcassandra Manual
Author: <insert document author here>
Abstract: This manual describes what libcassandra is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libcassandra/libcassandra.sgml.gz

Format: postscript
Files: /usr/share/doc/libcassandra/libcassandra.ps.gz

Format: text
Files: /usr/share/doc/libcassandra/libcassandra.text.gz

Format: HTML
Index: /usr/share/doc/libcassandra/html/index.html
Files: /usr/share/doc/libcassandra/html/*.html
